# Prometheus configuration for VPN Proxy monitoring

global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    monitor: 'vpn-proxy'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - '/etc/prometheus/rules/*.yml'

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # VPN Proxy Auth Service
  - job_name: 'vpn-proxy-auth'
    static_configs:
      - targets: ['proxy-auth:9090']
        labels:
          service: 'proxy-auth'
    metrics_path: '/metrics'

  # Traefik metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik-proxy:8090']
        labels:
          service: 'traefik-proxy'
    metrics_path: '/metrics'

  # VPN Proxy Server (Rust implementation)
  - job_name: 'vpn-proxy-server'
    static_configs:
      - targets: ['vpn-proxy:9090']
        labels:
          service: 'vpn-proxy'
    metrics_path: '/metrics'

# Remote write configuration (optional)
# remote_write:
#   - url: http://remote-prometheus:9090/api/v1/write