[workspace]
resolver = "2"
members = [
    "crates/vpn-docker",
    "crates/vpn-crypto",
    "crates/vpn-network",
    "crates/vpn-users",
    "crates/vpn-server",
    "crates/vpn-monitor",
    "crates/vpn-cli", 
    "crates/vpn-runtime",
    "crates/vpn-containerd",
    "crates/vpn-telemetry",
    "crates/vpn-compose",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["VPN Project Team"]
license = "MIT"
repository = "https://github.com/your-org/vpn-rust"

[workspace.dependencies]
tokio = { version = "1.35", features = ["full"] }
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"

# Docker
bollard = "0.15"

# Cryptography
base64 = "0.21"
uuid = { version = "1.6", features = ["v4", "serde"] }
qrcode = "0.14"
image = "0.24"
x25519-dalek = "1.1"
rand = "0.8"
hex = "0.4"

# Network
ipnetwork = "0.20"
pnet = "0.34"

# CLI
toml = "0.8"
dialoguer = "0.11"

# Testing
proptest = "1.4"
quickcheck = "1.0"
mockall = "0.12"
console = "0.15"
indicatif = "0.17"
colored = "2.0"
tabled = "0.15"
clap = { version = "4.0", features = ["derive"] }

