site_name: VPN Manager - Python Implementation
site_description: Comprehensive VPN management system with Python/Pydantic/TUI stack
site_author: VPN Manager Team
site_url: https://vpn-manager.readthedocs.io

repo_name: vpn-manager/vpn-python
repo_url: https://github.com/vpn-manager/vpn-python
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.action.edit

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vpn-manager/vpn-python
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/vpnmanager/vpn-python

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - autorefs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - CLI Commands: user-guide/cli-commands.md
    - TUI Interface: user-guide/tui-interface.md
    - User Management: user-guide/user-management.md
    - Server Management: user-guide/server-management.md
    - Proxy Services: user-guide/proxy-services.md
    - Monitoring: user-guide/monitoring.md
  - Administrator Guide:
    - Installation & Setup: admin-guide/installation.md
    - Server Configuration: admin-guide/server-config.md
    - Security: admin-guide/security.md
    - Backup & Recovery: admin-guide/backup-recovery.md
    - Troubleshooting: admin-guide/troubleshooting.md
  - Migration:
    - From Rust Version: migration/from-rust.md
    - Configuration Migration: migration/config-migration.md
    - Data Migration: migration/data-migration.md
  - API Reference:
    - Core Models: api/models.md
    - Services: api/services.md
    - CLI: api/cli.md
    - Protocols: api/protocols.md
  - Development:
    - Architecture: development/architecture.md
    - Contributing: development/contributing.md
    - Testing: development/testing.md
    - Performance: development/performance.md
  - Deployment:
    - Docker: deployment/docker.md
    - Production: deployment/production.md
    - Scaling: deployment/scaling.md
    - CI/CD: deployment/cicd.md