apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-operator
  namespace: vpn-system
spec:
  template:
    spec:
      containers:
      - name: operator
        env:
        - name: LOG_LEVEL
          value: info
        - name: LOG_FORMAT
          value: json