# Grafana Datasource Configuration
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s
    
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: false
    jsonData:
      tracesToMetrics:
        datasourceUid: prometheus
        tags:
          - key: service.name
            value: service
          - key: http.status_code
            value: status_code
        queries:
          - name: Request Duration
            query: 'sum(rate(http_request_duration_seconds_bucket{service="$service",status_code="$status_code"}[5m])) by (le)'
          - name: Request Rate
            query: 'sum(rate(http_requests_total{service="$service",status_code="$status_code"}[5m]))'
            
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      timeout: 60
      maxLines: 1000