apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vpn-system

bases:
- ../../base

commonLabels:
  environment: production
  
replicas:
- name: vpn-operator
  count: 2

images:
- name: your-registry/vpn-operator
  newTag: v0.1.0-prod

configMapGenerator:
- name: vpn-operator-config
  behavior: merge
  literals:
  - enableHA=true
  - metricsPort=8080
  - webhookPort=9443

patchesStrategicMerge:
- patches/deployment.yaml
- patches/resources.yaml

resources:
- monitoring/service-monitor.yaml
- monitoring/network-policy.yaml