# Development Environment Override
# Use with: docker-compose -f base.yml -f development.yml up
version: '3.8'

services:
  vpn-server:
    environment:
      - XRAY_LOG_LEVEL=debug
      - DEV_MODE=true
    ports:
      - "8080:8080"  # Expose debug port
    volumes:
      - ../debug:/debug  # Debug output directory

  vpn-api:
    environment:
      - NODE_ENV=development
      - DEBUG=true
      - LOG_LEVEL=debug
    ports:
      - "9229:9229"  # Node.js debug port
    volumes:
      - ./src:/app/src:ro  # Hot reload for development
      - /app/node_modules

  nginx-proxy:
    environment:
      - NGINX_LOG_LEVEL=debug
    volumes:
      - ./configs/nginx/dev:/etc/nginx/conf.d:ro

  postgres:
    environment:
      - POSTGRES_LOG_STATEMENT=all
      - POSTGRES_LOG_MIN_DURATION_STATEMENT=0
    ports:
      - "5432:5432"  # Expose database for development tools

  redis:
    ports:
      - "6379:6379"  # Expose Redis for development tools
    command: redis-server --appendonly yes --loglevel debug

  # Development-only services
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: vpn-pgadmin-dev
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@vpn.local
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    networks:
      - vpn-internal
    depends_on:
      - postgres

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: vpn-redis-commander-dev
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379:0:${REDIS_PASSWORD:-changepassword}
    networks:
      - vpn-internal
    depends_on:
      - redis

  # Hot reload file watcher for configuration changes
  file-watcher:
    image: node:18-alpine
    container_name: vpn-file-watcher-dev
    working_dir: /app
    volumes:
      - ./configs:/app/configs:ro
      - ./scripts:/app/scripts:ro
    command: ["npm", "run", "watch"]
    networks:
      - vpn-internal
    profiles:
      - dev-tools