apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vpn-system

resources:
- ../../../manifests/crd.yaml
- ../../../manifests/rbac.yaml
- ../../../manifests/deployment.yaml

commonLabels:
  app.kubernetes.io/name: vpn-operator
  app.kubernetes.io/managed-by: kustomize

images:
- name: vpn-operator:latest
  newName: your-registry/vpn-operator
  newTag: v0.1.0

configMapGenerator:
- name: vpn-operator-config
  literals:
  - vpnImage=vpn-server:latest
  - defaultProtocol=vless
  - enableHA=false

patchesStrategicMerge:
- patches/deployment.yaml