apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vpn-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vpn-operator.labels" . | nindent 4 }}
data:
  config.yaml: |
    namespace: {{ .Values.operator.watchNamespace | quote }}
    vpnImage: {{ .Values.operator.vpnImage | quote }}
    defaultProtocol: {{ .Values.operator.defaultProtocol | quote }}
    enableHA: {{ .Values.operator.enableHA }}
    metricsPort: {{ .Values.metrics.port }}
    webhookPort: {{ .Values.webhook.port }}
    leaderElection: {{ .Values.operator.leaderElection.enabled }}
    resourceLimits:
      cpuRequest: "100m"
      cpuLimit: "500m"
      memoryRequest: "128Mi"
      memoryLimit: "512Mi"