
version: '3.8'
services:
  vpn-server:
    image: ghcr.io/xtls/xray-core:latest
    container_name: vpn-server
    ports:
      - "${VPN_PORT:-8443}:8443"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
networks:
  vpn-network:
    driver: bridge
volumes:
  vpn-data:
    driver: local
