# Traefik Security Headers Middleware Configuration

http:
  middlewares:
    # Security headers middleware
    security-headers:
      headers:
        # HSTS
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        
        # Security headers
        customFrameOptionsValue: "DENY"
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
        
        # CSP Header
        contentSecurityPolicy: |
          default-src 'self';
          script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net;
          style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
          font-src 'self' https://fonts.gstatic.com;
          img-src 'self' data: https:;
          connect-src 'self' wss: https:;
          frame-ancestors 'none';
          base-uri 'self';
          form-action 'self';
          
        # Feature Policy
        featurePolicy: |
          camera 'none';
          microphone 'none';
          payment 'none';
          usb 'none';
          geolocation 'none';
          
        # Custom headers
        customResponseHeaders:
          X-Robots-Tag: "noindex, nofollow, nosnippet, noarchive, noimageindex"
          X-Permitted-Cross-Domain-Policies: "none"
          Expect-CT: "max-age=86400, enforce"
          
    # Rate limiting middleware
    rate-limit:
      rateLimit:
        average: 100
        period: 1m
        burst: 200
        
    # IP whitelist middleware (for admin endpoints)
    ip-whitelist:
      ipWhiteList:
        sourceRange:
          - "10.0.0.0/8"
          - "172.16.0.0/12"
          - "192.168.0.0/16"
          # Add your admin IP ranges here
          
    # Basic auth middleware (backup authentication)
    basic-auth:
      basicAuth:
        usersFile: /etc/traefik/users/.htpasswd
        realm: "VPN Admin Area"
        
    # Compress responses
    compress:
      compress:
        excludedContentTypes:
          - text/event-stream
          
    # Add request ID for tracing
    request-id:
      plugin:
        requestId:
          headerName: "X-Request-ID"
          
  # TLS Options
  tls:
    options:
      secure:
        minVersion: VersionTLS12
        preferServerCipherSuites: true
        cipherSuites:
          - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
          - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
          - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
          - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
          - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
          - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
        curvePreferences:
          - CurveP521
          - CurveP384
        sniStrict: true