# Prometheus Configuration for VPN System
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'vpn-system'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert_rules.yml"

# Scrape configuration
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 15s

  # VPN Server metrics
  - job_name: 'vpn-server'
    static_configs:
      - targets: ['vpn-server:8080']
    metrics_path: /stats/prometheus
    scrape_interval: 30s
    scrape_timeout: 10s

  # VPN API metrics
  - job_name: 'vpn-api'
    static_configs:
      - targets: ['vpn-api:3000']
    metrics_path: /metrics
    scrape_interval: 15s
    basic_auth:
      username: 'metrics'
      password: 'metrics_password'

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-proxy:8080']
    metrics_path: /nginx_status
    scrape_interval: 15s

  # PostgreSQL metrics (if using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: /metrics
    scrape_interval: 30s

  # Redis metrics (if using redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    metrics_path: /metrics
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: /metrics
    scrape_interval: 15s

  # Docker daemon metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['172.20.0.1:9323']
    metrics_path: /metrics
    scrape_interval: 30s

  # Container metrics via cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: /metrics
    scrape_interval: 30s

  # Custom VPN telemetry metrics
  - job_name: 'vpn-telemetry'
    static_configs:
      - targets: ['vpn-api:3001']
    metrics_path: /telemetry/prometheus
    scrape_interval: 15s
    scrape_timeout: 10s

# Remote write configuration (optional)
# remote_write:
#   - url: "https://your-remote-prometheus.com/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB