# Development Environment Configuration
# Optimized for local development with debugging and tooling

version: '3.8'

services:
  # Development-specific overrides
  vpn-server:
    environment:
      - DEBUG=true
      - LOG_LEVEL=debug
      - ENABLE_PROFILING=true
    volumes:
      # Mount source code for hot reloading
      - ./src:/app/src:ro
      - ./config:/app/config:rw
    ports:
      # Expose debug ports
      - "9229:9229"  # Node.js debug port
      - "6060:6060"  # Go pprof port
      - "9090:9090"  # Prometheus metrics

  # Development database with exposed port
  postgres:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=dev_password

  # Redis with exposed port for debugging
  redis:
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --loglevel debug

  # Development tools
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    networks:
      - vpn-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - vpn-network

  # Mailhog for email testing
  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - vpn-network

# Development network configuration
networks:
  vpn-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16