# Staging Environment Configuration
# Pre-production environment that mirrors production settings

version: '3.8'

services:
  # Staging-specific overrides
  vpn-server:
    environment:
      - ENVIRONMENT=staging
      - LOG_LEVEL=info
      - ENABLE_METRICS=true
      - ENABLE_TRACING=true
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Staging database with replication
  postgres:
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_REPLICATION_MODE=master
      - POSTGRES_REPLICATION_USER=replicator
      - POSTGRES_REPLICATION_PASSWORD_FILE=/run/secrets/replication_password
    secrets:
      - postgres_password
      - replication_password
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G

  postgres-replica:
    image: postgres:15-alpine
    environment:
      - POSTGRES_REPLICATION_MODE=slave
      - POSTGRES_MASTER_HOST=postgres
      - POSTGRES_REPLICATION_USER=replicator
      - POSTGRES_REPLICATION_PASSWORD_FILE=/run/secrets/replication_password
    secrets:
      - replication_password
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    networks:
      - vpn-network

  # Redis with persistence
  redis:
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Staging monitoring stack
  prometheus:
    environment:
      - ENVIRONMENT=staging
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  grafana:
    environment:
      - GF_SECURITY_ADMIN_PASSWORD_FILE=/run/secrets/grafana_password
      - GF_SERVER_ROOT_URL=https://staging-grafana.vpn.example.com
    secrets:
      - grafana_password
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

# Staging secrets
secrets:
  postgres_password:
    external: true
    name: staging_postgres_password
  replication_password:
    external: true
    name: staging_replication_password
  grafana_password:
    external: true
    name: staging_grafana_password

# Staging networks
networks:
  vpn-network:
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 10.1.0.0/16