apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vpn-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/vpn-operator
    targetRevision: HEAD
    path: deploy/helm/vpn-operator
    helm:
      values: |
        operator:
          replicas: 2
          image:
            repository: your-registry/vpn-operator
            tag: v0.1.0
          enableHA: true
          
        metrics:
          enabled: true
          service:
            annotations:
              prometheus.io/scrape: "true"
              prometheus.io/port: "8080"
        
        webhook:
          enabled: true
          certManager:
            enabled: true
        
        monitoring:
          serviceMonitor:
            enabled: true
            namespace: monitoring
            labels:
              prometheus: kube-prometheus
          
          grafanaDashboard:
            enabled: true
            namespace: monitoring
  
  destination:
    server: https://kubernetes.default.svc
    namespace: vpn-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 3