apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vpnservers.vpn.io
spec:
  group: vpn.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - protocol
            - port
            - users
            properties:
              protocol:
                type: string
                enum: ["vless", "outline", "wireguard", "openvpn"]
              port:
                type: integer
                minimum: 1024
                maximum: 65535
              replicas:
                type: integer
                minimum: 1
                maximum: 10
                default: 1
              highAvailability:
                type: boolean
                default: false
              resources:
                type: object
                properties:
                  cpuRequest:
                    type: string
                    default: "100m"
                  cpuLimit:
                    type: string
                    default: "500m"
                  memoryRequest:
                    type: string
                    default: "128Mi"
                  memoryLimit:
                    type: string
                    default: "512Mi"
                  storageSize:
                    type: string
                    default: "1Gi"
              users:
                type: object
                required:
                - maxUsers
                properties:
                  maxUsers:
                    type: integer
                    minimum: 1
                  autoCreate:
                    type: boolean
                    default: false
                  quotaGb:
                    type: integer
                    minimum: 0
                    default: 0
                  externalAuth:
                    type: object
                    properties:
                      authType:
                        type: string
                        enum: ["ldap", "oauth2", "oidc", "saml"]
                      endpoint:
                        type: string
                      secretName:
                        type: string
              network:
                type: object
                properties:
                  serviceType:
                    type: string
                    enum: ["ClusterIP", "NodePort", "LoadBalancer"]
                    default: "ClusterIP"
                  loadBalancerSourceRanges:
                    type: array
                    items:
                      type: string
                  nodePort:
                    type: integer
                    minimum: 30000
                    maximum: 32767
                  enableIpv6:
                    type: boolean
                    default: false
              security:
                type: object
                properties:
                  enableTls:
                    type: boolean
                    default: true
                  tlsSecret:
                    type: string
                  enableFirewall:
                    type: boolean
                    default: true
                  allowedIps:
                    type: array
                    items:
                      type: string
                  enableIds:
                    type: boolean
                    default: false
              monitoring:
                type: object
                properties:
                  enableMetrics:
                    type: boolean
                    default: true
                  metricsPort:
                    type: integer
                    default: 9090
                  enableTracing:
                    type: boolean
                    default: false
                  tracingEndpoint:
                    type: string
              labels:
                type: object
                additionalProperties:
                  type: string
              annotations:
                type: object
                additionalProperties:
                  type: string
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Creating", "Running", "Updating", "Degraded", "Failed", "Terminating"]
              message:
                type: string
              readyReplicas:
                type: integer
              replicas:
                type: integer
              activeUsers:
                type: integer
              totalTrafficBytes:
                type: integer
              endpoint:
                type: string
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
                    lastTransitionTime:
                      type: string
              lastUpdated:
                type: string
    additionalPrinterColumns:
    - name: Protocol
      type: string
      jsonPath: .spec.protocol
    - name: Port
      type: integer
      jsonPath: .spec.port
    - name: Status
      type: string
      jsonPath: .status.phase
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: vpnservers
    singular: vpnserver
    kind: VpnServer
    shortNames:
    - vpn