apiVersion: v1
kind: Namespace
metadata:
  name: vpn-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-operator
  namespace: vpn-system
  labels:
    app: vpn-operator
    app.kubernetes.io/name: vpn-operator
    app.kubernetes.io/component: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpn-operator
  template:
    metadata:
      labels:
        app: vpn-operator
        app.kubernetes.io/name: vpn-operator
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: vpn-operator
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      containers:
      - name: operator
        image: vpn-operator:latest
        imagePullPolicy: IfNotPresent
        command:
        - /usr/local/bin/vpn-operator
        args:
        - --metrics-port=8080
        - --webhook-port=9443
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - name: metrics
          containerPort: 8080
          protocol: TCP
        - name: webhook
          containerPort: 9443
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: webhook-certs
          mountPath: /tmp/k8s-webhook-server/serving-certs
          readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: vpn-operator-webhook-certs
          optional: true
---
apiVersion: v1
kind: Service
metadata:
  name: vpn-operator-metrics
  namespace: vpn-system
  labels:
    app: vpn-operator
spec:
  selector:
    app: vpn-operator
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: vpn-operator-webhook
  namespace: vpn-system
  labels:
    app: vpn-operator
spec:
  selector:
    app: vpn-operator
  ports:
  - name: webhook
    port: 443
    targetPort: webhook