# VPN Proxy Authentication Service Configuration

# Proxy protocol configuration
protocol = "both"  # http, socks5, or both
bind_host = "0.0.0.0"
http_port = 8080
socks5_port = 1080

# Authentication configuration
[auth]
enabled = true
backend = "vpn-users"  # vpn-users, file, ldap, or http
cache_ttl = { secs = 300, nanos = 0 }  # 5 minutes
allow_anonymous = false
ip_whitelist = [
    "127.0.0.1",
    "172.30.0.0/16",  # Docker network
]

# Rate limiting configuration
[rate_limit]
enabled = true
requests_per_second = 100
burst_size = 200
bandwidth_limit = 10485760  # 10 MB/s per user
global_limit = 10000  # Total RPS for all users

# Connection pool configuration
[pool]
max_connections_per_host = 100
max_total_connections = 1000
idle_timeout = { secs = 300, nanos = 0 }  # 5 minutes
max_lifetime = { secs = 3600, nanos = 0 }  # 1 hour

# Metrics configuration
[metrics]
enabled = true
bind_address = "0.0.0.0:9090"
path = "/metrics"

# Timeout configuration
[timeouts]
connect = { secs = 10, nanos = 0 }
read = { secs = 30, nanos = 0 }
write = { secs = 30, nanos = 0 }
idle = { secs = 300, nanos = 0 }

# Logging
log_level = "info"