# Traefik High Availability Configuration
# This configuration enables Traefik clustering with shared state

global:
  checkNewVersion: false
  sendAnonymousUsage: false

# Enable cluster mode with Consul as backend
cluster:
  store: consul
  prefix: traefik

# Entry points
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  
  websecure:
    address: ":443"
    http:
      tls:
        options: default
  
  vpn-xray:
    address: ":8443"
  
  metrics:
    address: ":8080"

# Enable API and dashboard
api:
  dashboard: true
  debug: true
  insecure: false

# Providers
providers:
  # Docker provider
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: vpn-network
    watch: true
    
  # Consul for service discovery and configuration
  consul:
    endpoints:
      - "consul-1:8500"
      - "consul-2:8500"
      - "consul-3:8500"
    watch: true
    
  # File provider for static configurations
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

# Certificate resolvers with Consul storage
certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@vpn.local
      storage: "consul"
      keyType: EC256
      httpChallenge:
        entryPoint: web
      # DNS challenge for wildcard certificates
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
        delayBeforeCheck: 60s

# Consul configuration for shared state
consul:
  endpoints:
    - "consul-1:8500"
    - "consul-2:8500"
    - "consul-3:8500"
  username: "traefik"
  password: "${CONSUL_TRAEFIK_PASSWORD}"
  pollInterval: "5s"
  pollTimeout: "5s"

# Logging
log:
  level: INFO
  format: json
  filePath: /var/log/traefik/traefik.log

# Access logs
accessLog:
  format: json
  filePath: /var/log/traefik/access.log
  filters:
    statusCodes:
      - "400-599"
  fields:
    headers:
      defaultMode: keep
      names:
        User-Agent: redact
        Authorization: drop
        X-Forwarded-For: keep

# Metrics for Prometheus with HA labels
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true
    entryPoint: metrics
    addMetricsLabels:
      traefik_instance: "${TRAEFIK_INSTANCE_ID}"
      traefik_cluster: "${TRAEFIK_CLUSTER_NAME:-vpn-cluster}"

# Health check endpoint
ping:
  entryPoint: metrics

# Tracing for Jaeger
tracing:
  jaeger:
    samplingServerURL: "http://jaeger:14268/api/sampling"
    samplingType: const
    samplingParam: 1.0
    localAgentHostPort: "jaeger:6832"
    traceContextHeaderName: "uber-trace-id"